services:
  - type: web
    name: switchin
    runtime: static
    buildCommand: npm ci && npm run build -- --configuration production
    staticPublishPath: dist/switchin/browser
    pullRequestPreviewsEnabled: false
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
